schema {
    query: Query
}

# -------------------------------
# Queries
# -------------------------------
type Query {
    runForecastTest(input: ForecastInput): GenericResponse!

    getSKUsMetadata: GenericResponse!

    getSKUForecasts: GenericResponse!

    getMonthlyTotals: GenericResponse!
}

# -------------------------------
# Generic Lambda response
# -------------------------------
type GenericResponse {
    status: String!
    result: AWSJSON
}

# -------------------------------
# Input types
# -------------------------------
input ForecastInput {
    input_data: AWSJSON
}
