#!/bin/sh
set -uo pipefail

API="$AWS_LAMBDA_RUNTIME_API"

log() {
  echo "[bootstrap] $1" 1>&2
}

log "Starting R custom runtime..."

read_response() {
  RAW=$(curl -s -i "http://${API}/2018-06-01/runtime/invocation/next")

  # Extract Request ID from Lambda Runtime API header
  REQUEST_ID=$(printf "%s" "$RAW" \
    | grep -i "^Lambda-Runtime-Aws-Request-Id:" \
    | awk '{print $2}' \
    | tr -d '\r')

  # Extract only JSON body (after blank line)
  EVENT=$(printf "%s" "$RAW" | sed '1,/^\r$/d')
}

    # Call R
cat <<-'EOF' > /tmp/run_event.R
  library(jsonlite)
  tryCatch({
    args <- commandArgs(trailingOnly = TRUE)
    event <- fromJSON(file(args[1]), simplifyVector = FALSE)
    message("EVENT RECEIVED: ", toJSON(event))
    source("/var/task/entrypoint.R")
    result <- handler(event, NULL)
    cat(toJSON(result, auto_unbox = TRUE))
  }, error=function(e) {
    message("R ERROR: ", e$message)
    stop(e)
  })
EOF

while true; do
  log "Requesting next event..."
    read_response

    if [ -z "$REQUEST_ID" ]; then
      log "ERROR: No requestId in event"
      continue
    fi

    log "Received requestId: $REQUEST_ID"

    echo "$EVENT" > /tmp/event.json
    if RESPONSE=$(Rscript /tmp/run_event.R /tmp/event.json); then
      log "Posting response for $REQUEST_ID"
      curl -s -X POST \
        "http://${API}/2018-06-01/runtime/invocation/${REQUEST_ID}/response" \
        -d "$RESPONSE"
    else
      ERROR="{\"errorMessage\": \"R failed\"}"
      log "R ERROR — Posting error back to Lambda..."
      curl -s -X POST \
        "http://${API}/2018-06-01/runtime/invocation/${REQUEST_ID}/error" \
        -d "$ERROR"
      continue
    fi

done
